[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  environment = { VITE_API_URL = "https://hfrat-backend.onrender.com" }

[context.deploy-preview]
  environment = { VITE_API_URL = "https://hfrat-backend.onrender.com" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
